### ISSUE TITLE
Candidate table: show applied filtering in the URL

### ISSUE THREAD

**Issue by ddobie** [ADACS-Australia/YWang.VASTER#22]
Not sure how difficult it is, and in some ways this is actually a downgrade, but it would be useful to include the applied filtering parameters in the URL. This would allow specific filters to be revisited (e.g. if someone wants to carry out the same search every week as new data comes in) or to be easily shared between people (e.g. supervisors checking the work of their students).

This would save users the hassle of having to manually input the filters every time, which also may lead to inconsistencies.

**Comment by alexmassen-hane** [comment]
Completed in #29
