### ISSUE TITLE
Candidate rating page: Update Aladin zoom to sensible level

### ISSUE THREAD

**Issue by ddobie** [ADACS-Australia/YWang.VASTER#23]
By default the Aladin tool has an all-sky view. This should be changed to something like a 2 arcmin x 2 arcmin zoom.

**Comment by alexmassen-hane** [comment]
Completed in #29 - Default zoom is set to 2 arcmin in y-direction in the html template for the Candidate Rating page, x-direction is dependant on the width of the java applet size.
