### ISSUE TITLE
Candidates page: summary statistics

### ISSUE THREAD

**Issue by Elle-WANG** [ADACS-Australia/YWang.VASTER#26]
It would be good if we can also add a display window at bottom showing all parameters in the final_csv file for this particular object. It doesn't have to be well-formatted (a naive table should be fine) and can just display all/every parameters even we add new columns in final_csv file (less likely happen though)

Minor fix

- Move "MD Deep" from "Deep stats" to "Statistics" panel
- Add units for "sep" in "Spatial Details" panel (deep_sep is in unit of arcsec, beam_sep is in unit of degree, and bright_sep in unit of arcmin)
- Can round those numbers to 4 or 5 decimal places 
- replace "standard map" to "standard deviation" 
- Show name in the candidate page (based on "name" column in final_csv)
- Add flitering based on people's rating and tags/labels 

Other fix if we have enough time

- Ideally make the web link contains name/SBID/beam information, e.g. ywangvaster.duckdns.org/candidate_rating/sbid=50230?beam=01?name=J043024.66-615211.55? (something like this) 
- Add a slider bar for "slices" display, and add an input panel allowing us to specify the number of image to display (sometimes can get > 3000 images and it would be really good to have this function

**Comment by Elle-WANG** [comment]
Edit: Move "MD Deep" from "Deep stats" to "Statistics" panel and change the name to "modulation index"

**Comment by Elle-WANG** [comment]
Typo: panel name "Statitics" -> "Statistics"

**Comment by alexmassen-hane** [comment]
Completed in #29
