### ISSUE TITLE
ATNF Pulsar Catalogue

### ISSUE THREAD

**Issue by alexmassen-hane** [ADACS-Australia/YWang.VASTER#3]
Ensure that that the ATNF catalogue is loaded properly on start up and periodically updated with some form of cron job.

**Comment by PaulHancock** [comment]
Fixing the issue with the new "database" format from ATNF: https://github.com/ADACS-Australia/GleamXGPMonitoring/blob/dev/gleam_webapp/candidate_app/management/commands/refresh_pulsar_table.py

**Comment by PaulHancock** [comment]
Example of a cron job that runs within a container: [Docs](https://github.com/ADACS-Australia/goto-xbs/wiki/RunATaskPeriodically)

Requires that `cron` is installed when the container builds [docker file](https://github.com/ADACS-Australia/goto-xbs/blob/7f4f701fbfc34fe5924c3673f7fd5f5c7879e1fc/Dockerfile#L5), that the service is run when the container starts [compose file](https://github.com/ADACS-Australia/goto-xbs/blob/main/docker-compose.yml), and then a python script that manages the cron jobs [script](https://github.com/ADACS-Australia/goto-xbs/blob/main/cron_jobs.py)

**Comment by alexmassen-hane** [comment]
Completed in #29
